export interface MockTestItem {
    id: string;
    title: string;
    description: string;
    questions_count: number;
    time_limit_minutes: number;
    status: 'В ПРОЦЕССЕ' | 'ЧЕРНОВИК' | 'АРХИВ';
    target_group: string;
    created_at: string;
    score?: number;
    passed_at?: string;
}

const MOCK_AVAILABLE_TESTS: MockTestItem[] = [
    {
        id: "1",
        title: "Архитектура микросервисов и брокеры сообщений",
        description: "Оценка знаний по проектированию RabbitMQ, Kafka, паттернам Saga и Outbox в распределенных системах.",
        questions_count: 25,
        time_limit_minutes: 45,
        status: "В ПРОЦЕССЕ",
        target_group: "DEV-OPS-01",
        created_at: "12.08.2026",
    },
    {
        id: "2",
        title: "Протокол HTTP/3 и оптимизация сетевых стеков",
        description: "Тестирование навыков работы с QUIC, TLS 1.3 и настройкой Nginx/HAProxy под высокие нагрузки.",
        questions_count: 15,
        time_limit_minutes: 30,
        status: "В ПРОЦЕССЕ",
        target_group: "BACKEND-BE-02",
        created_at: "10.08.2026",
    },
    {
        id: "3",
        title: "Базы данных: Транзакции, ACID и индексы PostgreSQL",
        description: "Проверка понимания уровней изоляции транзакций, B-Tree/GIN индексов и оптимизации EXPLAIN ANALYZE.",
        questions_count: 30,
        time_limit_minutes: 60,
        status: "ЧЕРНОВИК",
        target_group: "DBA-SPEC-04",
        created_at: "05.08.2026",
    },
    {
        id: "4",
        title: "React 19 и паттерны управления состоянием",
        description: "Глубокий анализ Server Components, useOptimistic, Zustand и оптимизации повторных рендеров.",
        questions_count: 20,
        time_limit_minutes: 40,
        status: "В ПРОЦЕССЕ",
        target_group: "FRONTEND-FE-01",
        created_at: "04.08.2026",
    },
    {
        id: "5",
        title: "Docker, WSL2 и контейнеризация Laravel Sail",
        description: "Практические аспекты изолированной разработки, проброса портов и монтирования volumes.",
        questions_count: 18,
        time_limit_minutes: 35,
        status: "ЧЕРНОВИК",
        target_group: "DEV-OPS-01",
        created_at: "02.08.2026",
    },
    {
        id: "6",
        title: "Безопасность API: OAuth2, JWT и Rate Limiting",
        description: "Защита конечных точек RESTful API от подделки токенов, DDoS и атак методом перебора.",
        questions_count: 22,
        time_limit_minutes: 45,
        status: "В ПРОЦЕССЕ",
        target_group: "SEC-TEAM-01",
        created_at: "01.08.2026",
    },
    {
        id: "7",
        title: "Оптимизация производительности Eloquent ORM",
        description: "Устранение проблемы N+1 запросов, составные ключи, кастомные гидраторы и чанкирование.",
        questions_count: 16,
        time_limit_minutes: 30,
        status: "В ПРОЦЕССЕ",
        target_group: "BACKEND-BE-02",
        created_at: "29.07.2026",
    },
    {
        id: "8",
        title: "CI/CD пайплайны в GitLab и GitHub Actions",
        description: "Автоматическое тестирование, линтинг, сборка Docker-образов и деплой на staging-сервер.",
        questions_count: 24,
        time_limit_minutes: 50,
        status: "ЧЕРНОВИК",
        target_group: "DEV-OPS-01",
        created_at: "27.07.2026",
    },
    {
        id: "9",
        title: "Проектирование RESTful и gRPC сервисов",
        description: "Сравнение Protobuf и JSON, вызов бинарных RPC процедур и разработка межсервисных API.",
        questions_count: 20,
        time_limit_minutes: 40,
        status: "В ПРОЦЕССЕ",
        target_group: "BACKEND-BE-02",
        created_at: "25.07.2026",
    },
    {
        id: "10",
        title: "Мониторинг систем: Prometheus, Grafana и Jaeger",
        description: "Сбор метрик приложения, алертинг в Telegram, распределенный трассинг запросов.",
        questions_count: 28,
        time_limit_minutes: 55,
        status: "ЧЕРНОВИК",
        target_group: "DEV-OPS-01",
        created_at: "22.07.2026",
    },
];

const MOCK_PASSED_TESTS: MockTestItem[] = [
    {
        id: "101",
        title: "Безопасность веб-приложений и OWASP Top 10",
        description: "Аудит знаний по предотвращению XSS, CSRF, SQLi и корректной настройке CSP заголовков.",
        questions_count: 20,
        time_limit_minutes: 40,
        status: "В ПРОЦЕССЕ",
        target_group: "SEC-TEAM-01",
        created_at: "01.08.2026",
        score: 95,
        passed_at: "14.08.2026",
    },
    {
        id: "102",
        title: "Контейнеризация и оркестрация: Docker & K8s",
        description: "Базовый тест на составление multi-stage Dockerfile и конфигурацию Kubernetes Deployment/Ingress.",
        questions_count: 18,
        time_limit_minutes: 35,
        status: "В ПРОЦЕССЕ",
        target_group: "ALL-GROUPS",
        created_at: "20.07.2026",
        score: 82,
        passed_at: "11.08.2026",
    },
    {
        id: "103",
        title: "Основы алгоритмов и структур данных",
        description: "Оценка Big O нотации, работы с бинарными деревьями, связными списками и хэш-таблицами.",
        questions_count: 30,
        time_limit_minutes: 60,
        status: "В ПРОЦЕССЕ",
        target_group: "ALL-GROUPS",
        created_at: "15.07.2026",
        score: 90,
        passed_at: "08.08.2026",
    },
    {
        id: "104",
        title: "Сетевые протоколы: TCP/IP, DNS и TLS",
        description: "Анализ модели OSI, тройного рукопожатия TCP, структуры DNS запросов и TLS сертификатов.",
        questions_count: 22,
        time_limit_minutes: 45,
        status: "В ПРОЦЕССЕ",
        target_group: "DEV-OPS-01",
        created_at: "10.07.2026",
        score: 78,
        passed_at: "03.08.2026",
    },
    {
        id: "105",
        title: "Рефакторинг legacy-кода и паттерны GoF",
        description: "Идентификация запахов кода, применение паттернов Adapter, Strategy, Factory и Singleton.",
        questions_count: 25,
        time_limit_minutes: 50,
        status: "В ПРОЦЕССЕ",
        target_group: "BACKEND-BE-02",
        created_at: "05.07.2026",
        score: 88,
        passed_at: "28.07.2026",
    },
    {
        id: "106",
        title: "Тестирование с PHPUnit и Pest Framework",
        description: "Написание юнит и интеграционных тестов, мокирование сервисов, расчёт покрытия кода.",
        questions_count: 15,
        time_limit_minutes: 30,
        status: "В ПРОЦЕССЕ",
        target_group: "BACKEND-BE-02",
        created_at: "01.07.2026",
        score: 100,
        passed_at: "25.07.2026",
    },
    {
        id: "107",
        title: "Основы Linux, Bash-скрипты и SSH",
        description: "Управление правами доступа, автоматизация через cron, написание сценариев bash.",
        questions_count: 20,
        time_limit_minutes: 40,
        status: "В ПРОЦЕССЕ",
        target_group: "ALL-GROUPS",
        created_at: "25.06.2026",
        score: 85,
        passed_at: "20.07.2026",
    },
    {
        id: "108",
        title: "Работа с Redis и стратегии кэширования",
        description: "Паттерны Cache-Aside, Write-Through, структура данных Pub/Sub и Redis Cluster.",
        questions_count: 18,
        time_limit_minutes: 35,
        status: "В ПРОЦЕССЕ",
        target_group: "BACKEND-BE-02",
        created_at: "20.06.2026",
        score: 92,
        passed_at: "15.07.2026",
    },
    {
        id: "109",
        title: "Frontend сборка: Vite, Tailwind CSS и Webpack",
        description: "Настройка HMR, оптимизация CSS бандлов, Tree-shaking и плагины PostCSS.",
        questions_count: 16,
        time_limit_minutes: 30,
        status: "В ПРОЦЕССЕ",
        target_group: "FRONTEND-FE-01",
        created_at: "15.06.2026",
        score: 96,
        passed_at: "10.07.2026",
    },
    {
        id: "110",
        title: "Асинхронное программирование и Event Loop",
        description: "Понимание неблокирующего ввода-вывода, Promise, async/await и микрозадач в JS/Node.js.",
        questions_count: 24,
        time_limit_minutes: 45,
        status: "В ПРОЦЕССЕ",
        target_group: "FRONTEND-FE-01",
        created_at: "10.06.2026",
        score: 84,
        passed_at: "05.07.2026",
    },
];


export {
    MOCK_AVAILABLE_TESTS,
    MOCK_PASSED_TESTS,
}